name: 5.0-dev

on:
  push:
    paths:
      - ".github/workflows/build_5_0-dev.yml"
      - "5.0/**"
      - "overlay/**"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./5.0/VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./5.0/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            bcgdesign/aspnet:dev
            bcgdesign/aspnet:${{ steps.version.outputs.content }}-dev
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
